replace scss '>>>' with '::ng-deep' since the former causes compilation error
The error being:
```
./projects/laji/src/app/shared-modules/app-component/app.component.scss?ngResource
- Error: Module build failed (from
  ./node_modules/sass-loader/dist/cjs.js):
  Cannot read properties of undefined (reading 'column')
```

which led to this issue:

https://github.com/angular/angular-cli/issues/25134